language: ruby
addons:
  apt:
    packages:
      - xclip
      - xdotool
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3

script:
  - npm install -g markdownlint-cli
  - markdownlint *.md
  - rake
