name: Ruby

on: [push]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [2.6.x, 2.5.x, 2.4.x, 2.3.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Setup dependencies
      run: sudo apt-get install xclip xdotool
    - name: Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    - name: Tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake spec
